package main

const (
	aCoalesce                 = 'c'
	aReverse                  = 'r'
	aReorder                  = 'o'
	aLineDrop                 = 'l'
	aDebugPolygon             = '@'
	aPolygonDrop              = 'p'
	aDetectSharedBorders      = 'b'
	aPreferRadixSort          = 'R'
	aCalculateFeatureDensity  = 'g'
	aIncreaseGammaAsNeeded    = 'G'
	aMegerPolygonsAsNeeded    = 'm'
	aDropDensestAsNeeded      = 's'
	aDropFractionAsNeeded     = 'd'
	aDropSmallestAsNeeded     = 'n'
	aCoalesceDensestAsNeeded  = 'S'
	aCoalesceSmallestAsNeeded = 'N'
	aCoalesceFractionAsNeeded = 'D'
	aGridLowZooms             = 'L'
	aDetectWraparound         = 'w'
	aExtendZooms              = 'e'
	aClusterDensestAsNeeded   = 'C'
	aGenerateIDs              = 'i'
	aConvertNumericIDs        = 'I'
	aHilbert                  = 'h'

	pSimplify                   = 's'
	pSimplifyLow                = 'S'
	pSimplifySharedNodes        = 'n'
	pFeatureLimit               = 'f'
	pKiloByteLimit              = 'k'
	pDynamicDrop                = 'd'
	pInputOrder                 = 'i'
	pPolgongSplit               = 'p'
	pClipping                   = 'c'
	pDuplication                = 'D'
	pTinyPolygonReduction       = 't'
	pTileCompression            = 'C'
	pTileStats                  = 'g'
	pUseSourcePolygonWinding    = 'w'
	pReversSourcePolygonWinding = 'W'
	pEmptyCSVColumns            = 'e'
)
